@startuml
package models {
    class Client {
        -String name
        -String identificationNumber
        -IdentificationType identificationType
        -Date birthday
        -String address
        -String email
        -String phoneNumber
        -Collection<Account> accounts
        -Collection<Account> sharedAccounts
    }

    class IdentificationType {
        -String name
        -String symbol
    }

    class Account {
        -double balance
        -Client owner
        -String id
        -boolean allowDebt
        -Collection<Client> sharedClients
        -Collection<Cashflow> cashflows
    }

    class Cashflow {
        -Date date
        -double value
        -CashflowRate rate
    }

    class CashflowRate {
        -Date startedAd
        -double value
    }

    Client "1" *-- "0..*" Account : owner
    Client "0..*" *-- "0..*" Account : shared
    Client "0..*" -- "1" IdentificationType
    Account "1" *-- "0..*" Cashflow
    Cashflow "0..*" -- "1" CashflowRate
}

package controllers {
    class Bank {
        -Collection<Client> clients
        -Collection<Account> accounts
        -Collection<CashflowRate> rates
        +boolean hasClient(String clientID, String idType)
        +void createClient(String clientID, String idType, String name, Date birthday, String email, String phoneNumber, String address)
        +void changeClient(String clientID, String idType, String name, Date birthday, String email, String phoneNumber, String address)
        +boolean hasClients()
        +Collection<Client> getClients()
        +boolean isAmountValid(double amount, boolean allowDebt)
        +String createAccount(String clientID, String clientIDType, boolean allowDebt, double initialAmount)
        +boolean hasAccount(String accountID)
        +void shareAccount(String clientID, String clientIDType, String accountID, String sharedclientID, String sharedclientIDType)
        +boolean isAuthorized(String clientID, String clientIDType, String accountID)
        +boolean isCashflowAllowed(String accountID, double amount)
        +void registerCashflow(String clientID, String clientIDType, String accountID, double amount)
        +Account getAccount(String accountID)
        +void save(String filename)
        +{static}Bank load(String filename)
    }
    Bank "1" *-- "0..*" Client
    Bank "1" *-- "0..*" Account
    Bank "1" *-- "0..*" CashflowRate
}

package views {
    class CLI
    class GUI
    class WebApp
}

CLI "0..*" -- "1" Bank
WebApp "0..*" -- "1" Bank
GUI "0..*" -- "1" Bank
@enduml